# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- script: docker run -i --rm -v $(pwd):/src trzeci/emscripten ls -al
  displayName: 'Verify docker mount'

- script: docker run -i --rm -v $(pwd):/src trzeci/emscripten emcc src/trees.c -O2 -s WASM=1 -s EXPORTED_FUNCTIONS=['_renderTree', '_getAddresses']  -s EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'cwrap'] -o trees.js -s ALLOW_MEMORY_GROWTH=1
  displayName: 'Build WebAssembly assets'

- script: ls -al 
  displayName: 'Verify output assets'

- script: cp web/* $(Build.ArtifactStagingDirectory)
  displayName: 'Copy web contents'

- script: cp trees.js $(Build.ArtifactStagingDirectory)
  displayName: 'Copy JavaScript loader'

- script: cp trees.wasm $(Build.ArtifactStagingDirectory)
  displayName: 'Copy Wasm'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'wasm-trees'
  